version: '3.8'

services:
  auth-service:
    build: ./auth
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: docker_auth
        awslogs-stream-prefix: auth-service

  guest-service:
    build: ./guest
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: guest_log
        awslogs-stream-prefix: guest-service

networks:
  default:
    driver: bridge
