version: '3'
services:
  guest:
    build: ./guest  # Dockerfile location for the guest service
    container_name: guest-service
    ports:
      - "3001:3001"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/aws/ecs/service-logs"
        awslogs-region: "us-west-2"
        awslogs-create-group: "true"

  auth:
    build: ./auth  # Dockerfile location for the auth service
    container_name: auth-service
    ports:
      - "3002:3002"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/aws/ecs/service-logs"
        awslogs-region: "us-east-1"
        awslogs-create-group: "true"

