version: '3.7'

services:
  auth-service:
    build: ./auth
    logging:
      driver: awslogs
      options:
        awslogs-group: "visi-log-group"
        awslogs-region: "us-east-1"
        awslogs-stream-prefix: "auth-service"

  guest-service:
    build: ./guest
    logging:
      driver: awslogs
      options:
        awslogs-group: "visi-log-group"
        awslogs-region: "us-east-1"
        awslogs-stream-prefix: "guest-service"
