version: '3'
services:
  guest:
    build: ./guest
    container_name: guest-service
    ports:
      - "3001:3001"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/aws/ecs/service-logs"
        awslogs-region: "us-east-1"
        awslogs-create-group: "true"

  auth:
    build: ./auth
    container_name: auth-service
    ports:
      - "3002:3002"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/aws/ecs/service-logs"
        awslogs-region: "us-east-1"
        awslogs-create-group: "true"
