version: '3.7'

services:
  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options:
        awslogs-group: "docker_auth"
        awslogs-region: "us-east-1"

  guest-service:
    build: ./guest
    container_name: guest-service
    ports:
      - "5001:5000"
    logging:
      driver: awslogs
      options:
        awslogs-group: "guest_log"
        awslogs-region: "us-east-1"
